
spring:
  application:
    name: highonmusic-songs
  cloud:
    loadbalancer:
      ribbon:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8181